name: Run Simple Calculator

on:
  push:
    paths:
      - 'simple_calculator.sh'
  workflow_dispatch:

jobs:
  run-calculator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Give execute permission to script
        run: chmod +x simple_calculator.sh

      - name: Run calculator script with sample input
        run: |
          echo -e "5\n3\n+" | ./simple_calculator.sh
